version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: --templates https://github.com/thePulpo/hustlehub/raw/templates/portainer/templates-2.0.json

volumes:
  portainer_data: